name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4
        id: release
        with:
          target-branch: main

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          lfs: true

      - name: Restore
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/restore
